services:
  spark-master:
    image: bitnami/spark:latest
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"   # Spark Web UI
      - "7077:7077"   # Spark RPC port, for workers can connect to
    networks:
      - thangquang

  spark-worker-1:
    image: bitnami/spark:latest
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "9091:8081"  # Spark Worker Web UI
    environment:
      - SPARK_MODE=Worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - thangquang

  spark-worker-2:
    image: bitnami/spark:latest
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "9092:8081"  # Spark Worker Web UI
    environment:
      - SPARK_MODE=Worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - thangquang

networks:
  thangquang:
    driver: bridge
